export interface ParsedCommit {
  hash: string
  authorName: string
  authorEmail: string
  date: string
  subject: string
  body: string
}

export interface MarkerResult {
  sha: string
  before: string
  after: string
  found: boolean
}

const PR_SYNC_MARKER_PREFIX = '<!-- pr-sync: sha='

export function parseMarker(body: string): MarkerResult {
  const lines = body.split('\n')
  const idx = lines.findIndex(l => l.trim().startsWith(PR_SYNC_MARKER_PREFIX))

  if (idx === -1) {
    return { sha: '', before: body, after: '', found: false }
  }

  const line = lines[idx].trim()
  const shaStart = PR_SYNC_MARKER_PREFIX.length
  const shaEnd = line.indexOf(' -->', shaStart)
  const sha = shaEnd === -1 ? line.slice(shaStart).trimEnd() : line.slice(shaStart, shaEnd)

  return {
    sha,
    before: lines.slice(0, idx).join('\n'),
    after: lines.slice(idx).join('\n'),
    found: true,
  }
}

export function buildMarker(sha: string): string {
  return `<!-- pr-sync: sha=${sha} -->`
}

export function parseRawLog(raw: string): ParsedCommit[] {
  const commits: ParsedCommit[] = []
  const blocks = raw.split('---COMMIT---').map(b => b.trim()).filter(b => b.length > 0)

  for (const block of blocks) {
    const lines = block.split('\n')
    if (lines.length < 5) continue
    commits.push({
      hash: lines[0],
      authorName: lines[1],
      authorEmail: lines[2],
      date: lines[3],
      subject: lines[4],
      body: lines.slice(5).join('\n').trim(),
    })
  }

  return commits
}

export function buildWhatChangedSection(commits: ParsedCommit[]): string {
  if (commits.length === 0) return '## What Changed\n\n*No new commits*'
  const list = commits.map(c => `- \`${c.hash.slice(0, 7)}\` ${c.subject}`).join('\n')
  return `## What Changed\n\n${list}`
}

export function buildSyncBody(
  existingBody: string,
  currentSha: string,
  newCommits: ParsedCommit[],
): string {
  const { found, before } = parseMarker(existingBody)
  const markerLine = buildMarker(currentSha)
  const whatChanged = buildWhatChangedSection(newCommits)
  const autoSection = `${markerLine}\n\n${whatChanged}\n`

  if (!found) {
    const trimmed = existingBody.trim()
    if (trimmed) {
      return `${trimmed}\n\n${autoSection}`
    }
    const skeleton = '## Why\n\n<!-- Why are these changes needed? -->\n\n## How to Test\n\n<!-- What should reviewers do to verify? -->\n\n---\n\n'
    return `${skeleton}${autoSection}`
  }

  const beforeTrimmed = before.trimEnd()
  return beforeTrimmed ? `${beforeTrimmed}\n\n${autoSection}` : autoSection
}

export function buildReviewerPrompt(commits: ParsedCommit[]): string {
  const lines = commits.map(c => {
    const bodyLines = c.body ? '\n' + c.body.split('\n').map(l => `  ${l}`).join('\n') : ''
    return `- \`${c.hash.slice(0, 7)}\` ${c.subject}${bodyLines}`
  })

  return `The following commits were just pushed to a pull request. Write a concise PR comment summarizing them — group by type (feat, fix, refactor, docs, chore, test, ci), call out anything security-sensitive or architectural, and flag what to pay attention to during review. No preamble or tags.\n\n${lines.join('\n')}`
}

export function formatPlainComment(commits: ParsedCommit[]): string {
  if (commits.length === 0) return 'No new commits.'
  const lines = commits.map(c => `- \`${c.hash.slice(0, 7)}\` ${c.subject}`)
  return `## New Commits\n\n${lines.join('\n')}\n\n---\n_Generated by agenthood pr-sync_`
}
